name: Earth
version: ${project.version}
main: com.mckd.earth.Earth
api-version: 1.12
commands:
  email:
    description: email setting
  pve_point_add:
    description: pve point add
  lobby:
    description: go to lobby
